"""full_stack_accounts_checkout_reviews

Revision ID: 8d35e994584d
Revises: e6cf6873f84e
Create Date: 2026-10-01 13:17:30.922536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d35e994584d'
down_revision: Union[str, Sequence[str], None] = 'e6cf6873f84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Extend the empty development schema without replacing its existing tables."""
    connection = op.get_bind()
    for table_name in ("customers", "orders"):
        table = sa.table(table_name, sa.column("id"))
        count = connection.execute(sa.select(sa.func.count()).select_from(table)).scalar_one()
        if count:
            raise RuntimeError(
                f"{table_name} contains rows; migrate existing account and delivery data before this revision"
            )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('carbohydrates', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fat', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fiber', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sugar', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sodium', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_food_id'), 'nutrition', ['food_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_reference', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("amount >= 0", name="ck_payments_amount_nonnegative"),
    sa.CheckConstraint("method = 'cash_on_delivery'", name="ck_payments_method_valid"),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'food_id', name='uq_reviews_customer_food')
    )
    op.create_index(op.f('ix_reviews_customer_id'), 'reviews', ['customer_id'], unique=False)
    op.create_index(op.f('ix_reviews_food_id'), 'reviews', ['food_id'], unique=False)
    op.add_column('customers', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('customers', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    op.add_column('foods', sa.Column('ingredients', sa.Text(), nullable=True))
    op.add_column('order_items', sa.Column('food_name', sa.String(length=150), nullable=False))
    op.add_column('orders', sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('delivery_name', sa.String(length=150), nullable=False))
    op.add_column('orders', sa.Column('delivery_email', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('delivery_phone', sa.String(length=30), nullable=False))
    op.add_column('orders', sa.Column('delivery_address', sa.String(length=500), nullable=False))
    op.add_column('orders', sa.Column('delivery_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("Downgrading would delete account, payment, nutrition, and review data")
